name: Publish version
on:
  push:
    tags:
    - 'v*'
jobs:
  npm-publish:
    name: Publish to NPM registry
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Use Node.js v12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: yarn install
    - name: Test module
      run: yarn test
    - name: Publish module
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
  github-release:
    name: Publish GitHub release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Use Node.js v12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: yarn install
    - name: Get release version
      id: getReleaseVersion
      run: echo ::set-output name=RELEASE_VERSION::${GITHUB_REF/refs\/tags\/v/}
    - name: Prepare release notes
      run: yarn conventional-changelog -r 2 -p angular | tail -n +6 | head -n -3 | tee RELEASE-NOTES.md
    - name: Create release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.getReleaseVersion.outputs.RELEASE_VERSION }}
        name: Release ${{ steps.getReleaseVersion.outputs.RELEASE_VERSION }}
        body_path: RELEASE-NOTES.md
        draft: false
        prerelease: false
        files: |
          RELEASE-NOTES.md
          LICENSE
